name: chik_chak
description: ChikChak 2.0 is coming

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.19.0
  intl: ^0.15.7
  mockito: ^4.0.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  test: ^1.5.1+1
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true